name = "fastapi"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_TOKEN = AcMEASQgZmIyZmY2ZGYtMDIzYS00MTY3LWIxYjEtODA0OTZmYTliNmJiYTIyYjdlNmI3Mjk0NGMzM2IwMGEwY2NmMDM5YTllMzE=
UPSTASH_REDIS_REST_URL = https://national-mallard-49924.upstash.io